language: php

php:
  - 7.1
env:
  global:
    - TARGET=test

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ppa:ondrej/php
    packages: &default_packages
      - libsodium-dev

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - pecl install -f libsodium-1.0.6

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS