language: php

php:
  - 7.1
env:
  global:
    - TARGET=test

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo chmod +x ./.travis-libsodium.sh && ./.travis-libsodium.sh
  - pecl install -f libsodium-1.0.6

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
 - make $TARGET